//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Model.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class curriculum
    {
        public int curriculum_id { get; set; }
        public int discipline_id { get; set; }
        public string specialization_code { get; set; }
        public int theory { get; set; }
        public int practice { get; set; }
        public int course { get; set; }
        public int consultation { get; set; }
        public int exam { get; set; }
        public int term_num { get; set; }
    
        public virtual discipline discipline { get; set; }
        public virtual specialization specialization { get; set; }
    }
}
