//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Model.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class teachers_workload
    {
        public int workload_id { get; set; }
        public string year { get; set; }
        public int teacher_id { get; set; }
        public int discipline_id { get; set; }
        public int group_id { get; set; }
        public int term_num { get; set; }
        public int sum { get; set; }
        public double in_week { get; set; }
        public int theory { get; set; }
        public int practice { get; set; }
        public int course { get; set; }
        public int consultation { get; set; }
        public int exam { get; set; }
    
        public virtual discipline discipline { get; set; }
        public virtual group group { get; set; }
        public virtual user user { get; set; }
    }
}
