//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Model.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class teachers_schedule
    {
        public int schedule_id { get; set; }
        public int teacher_id { get; set; }
        public int disciplines_id { get; set; }
        public int hours { get; set; }
        public int group_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual discipline discipline { get; set; }
        public virtual group group { get; set; }
        public virtual user user { get; set; }
    }
}
